import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { afterEach, beforeEach, test } from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "..");
const bin = path.join(repoRoot, "bin", "awesome-agents.js");
const fixture = path.join(repoRoot, "test", "fixtures", "touch-grass");

let tempRoot;
let home;

beforeEach(async () => {
  tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "awesome-agents-test-"));
  home = path.join(tempRoot, "home");
  await fs.mkdir(home, { recursive: true });
});

afterEach(async () => {
  await fs.rm(tempRoot, { recursive: true, force: true });
});

test("lists available profiles from a local source as JSON", () => {
  const result = runCli(["add", fixture, "--list", "--json"]);
  assert.equal(result.status, 0, result.stderr);

  const parsed = JSON.parse(result.stdout);
  assert.deepEqual(
    parsed.profiles.map((profile) => profile.slug),
    ["ios-tester", "ios-ux-ui-critic"]
  );
});

test("dry-run install does not write target files or registry", () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "codex",
    "--profile",
    "ios-tester",
    "--global",
    "--home",
    home,
    "--dry-run",
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const parsed = JSON.parse(result.stdout);
  assert.equal(parsed.operations[0].action, "would-install");
  assert.equal(existsSync(path.join(home, ".codex", "agents", "ios-tester.toml")), false);
  assert.equal(existsSync(path.join(home, ".awesome-agents", "installed.json")), false);
});

test("installs a Codex profile and records it in the registry", async () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "codex",
    "--profile",
    "ios-tester",
    "--global",
    "--home",
    home,
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const target = path.join(home, ".codex", "agents", "ios-tester.toml");
  const registry = path.join(home, ".awesome-agents", "installed.json");
  assert.equal(existsSync(target), true);
  assert.equal(existsSync(registry), true);

  const content = await fs.readFile(target, "utf8");
  assert.match(content, /Generated by awesome-agents/);
  assert.match(content, /name = "ios-tester"/);
  assert.match(content, /description = "Executes iOS app flows/);
  assert.match(content, /model = "gpt-5\.5"/);
  assert.match(content, /developer_instructions = '''/);

  const installed = JSON.parse(await fs.readFile(registry, "utf8"));
  assert.equal(installed.installs[0].profile, "ios-tester");
  assert.equal(installed.installs[0].harness, "codex");
});

test("installs Claude Code and OpenCode profile renderings", async () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "claude-code",
    "opencode",
    "--profile",
    "ios-ux-ui-critic",
    "--global",
    "--home",
    home,
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const claudeTarget = path.join(home, ".claude", "agents", "ios-ux-ui-critic.md");
  const opencodeTarget = path.join(home, ".config", "opencode", "agents", "ios-ux-ui-critic.md");
  assert.equal(existsSync(claudeTarget), true);
  assert.equal(existsSync(opencodeTarget), true);

  const claude = await fs.readFile(claudeTarget, "utf8");
  const opencode = await fs.readFile(opencodeTarget, "utf8");
  assert.match(claude, /name: ios-ux-ui-critic/);
  assert.match(claude, /model: opus/);
  assert.match(opencode, /mode: subagent/);
  assert.match(opencode, /edit: deny/);
});

test("use renders a single profile without installing", () => {
  const result = runCli(["use", `${fixture}@ios-tester`, "--agent", "codex", "--home", home]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /name = "ios-tester"/);
  assert.equal(existsSync(path.join(home, ".codex", "agents", "ios-tester.toml")), false);
});

test("remove deletes only generated installs", async () => {
  const install = runCli([
    "add",
    fixture,
    "--agent",
    "codex",
    "--profile",
    "ios-tester",
    "--global",
    "--home",
    home
  ]);
  assert.equal(install.status, 0, install.stderr);

  const target = path.join(home, ".codex", "agents", "ios-tester.toml");
  assert.equal(existsSync(target), true);

  const remove = runCli(["remove", "ios-tester", "--agent", "codex", "--global", "--home", home, "--json"]);
  assert.equal(remove.status, 0, remove.stderr);
  assert.equal(existsSync(target), false);

  const registry = JSON.parse(await fs.readFile(path.join(home, ".awesome-agents", "installed.json"), "utf8"));
  assert.deepEqual(registry.installs, []);
});

function runCli(args) {
  return spawnSync(process.execPath, [bin, ...args], {
    cwd: repoRoot,
    encoding: "utf8",
    env: {
      ...process.env,
      HOME: home,
      CODEX_HOME: "",
      CLAUDE_HOME: "",
      OPENCODE_CONFIG_DIR: "",
      XDG_CONFIG_HOME: ""
    }
  });
}
