import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { afterEach, beforeEach, test } from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "..");
const bin = path.join(repoRoot, "bin", "awesome-agents.js");
const fixture = path.join(repoRoot, "test", "fixtures", "touch-grass");

let tempRoot;
let home;

beforeEach(async () => {
  tempRoot = await fs.mkdtemp(path.join(os.tmpdir(), "awesome-agents-test-"));
  home = path.join(tempRoot, "home");
  await fs.mkdir(home, { recursive: true });
});

afterEach(async () => {
  await fs.rm(tempRoot, { recursive: true, force: true });
});

test("top-level help is grouped and colorized", () => {
  const result = runCli(["--help"], {
    NO_COLOR: "",
    FORCE_COLOR: "",
    TERM: "xterm-256color"
  });
  assert.equal(result.status, 0, result.stderr);

  assert.match(result.stdout, /\x1b\[1mUsage:\x1b\[0m awesome-agents <command> \[options\]/);
  assert.match(result.stdout, /Manage Profiles:/);
  assert.match(result.stdout, /Add Options:/);
  assert.match(result.stdout, /Examples:/);
  assert.match(result.stdout, /awesome-agents add owner\/repo --agent triage-agent/);
  assert.doesNotMatch(result.stdout, /Commands:\n/);
});

test("NO_COLOR disables ANSI in help", () => {
  const result = runCli(["--help"], {
    NO_COLOR: "1",
    FORCE_COLOR: "",
    TERM: "xterm-256color"
  });
  assert.equal(result.status, 0, result.stderr);

  assert.doesNotMatch(result.stdout, /\x1b\[[0-9;]*m/);
  assert.match(result.stdout, /Usage: awesome-agents <command> \[options\]/);
  assert.match(result.stdout, /Manage Profiles:/);
});

test("lists available profiles from a local source as JSON", () => {
  const result = runCli(["add", fixture, "--list", "--json"]);
  assert.equal(result.status, 0, result.stderr);

  const parsed = JSON.parse(result.stdout);
  assert.deepEqual(
    parsed.profiles.map((profile) => profile.slug),
    ["chief-of-staff", "ios-tester", "ios-ux-ui-critic"]
  );
});

test("add requires an explicit source", async () => {
  const project = path.join(tempRoot, "project");
  await fs.mkdir(project, { recursive: true });
  const result = runCli(["add"], {}, { cwd: project });
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /missing required argument 'source'|Specify a source/);
  assert.equal(existsSync(path.join(home, ".codex", "chief-of-staff.config.toml")), false);
  assert.equal(existsSync(path.join(home, ".codex", "ios-tester.config.toml")), false);
  assert.equal(existsSync(path.join(home, ".codex", "ios-ux-ui-critic.config.toml")), false);
});

test("dry-run install does not write target files or registry", () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "codex",
    "--profile",
    "ios-tester",
    "--global",
    "--home",
    home,
    "--dry-run",
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const parsed = JSON.parse(result.stdout);
  assert.equal(parsed.operations[0].action, "would-install");
  assert.equal(existsSync(path.join(home, ".codex", "ios-tester.config.toml")), false);
  assert.equal(existsSync(path.join(home, ".awesome-agents", "installed.json")), false);
});

test("installs a Codex profile and records it in the registry", async () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "codex",
    "--profile",
    "ios-tester",
    "--global",
    "--home",
    home,
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const target = path.join(home, ".codex", "ios-tester.config.toml");
  const registry = path.join(home, ".awesome-agents", "installed.json");
  assert.equal(existsSync(target), true);
  assert.equal(existsSync(registry), true);

  const content = await fs.readFile(target, "utf8");
  assert.match(content, /Generated by awesome-agents/);
  assert.match(content, /name = "ios-tester"/);
  assert.match(content, /description = "Executes iOS app flows/);
  assert.match(content, /model = "gpt-5\.5"/);
  assert.match(content, /developer_instructions = '''/);

  const installed = JSON.parse(await fs.readFile(registry, "utf8"));
  assert.equal(installed.installs[0].profile, "ios-tester");
  assert.equal(installed.installs[0].harness, "codex");
});

test("installs the chief-of-staff profile as a profile, not a skill", async () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "chief-of-staff",
    "--global",
    "--home",
    home,
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const target = path.join(home, ".codex", "chief-of-staff.config.toml");
  assert.equal(existsSync(target), true);

  const content = await fs.readFile(target, "utf8");
  assert.match(content, /name = "chief-of-staff"/);
  assert.match(content, /Installed identity: `chief-of-staff`/);
  assert.match(content, /Role\/name: `Chief Of Staff`/);
  assert.match(content, /operational agent profile, not a skill/);
  assert.doesNotMatch(content, /primary_skill: chief-of-staff/);
  assert.doesNotMatch(content, /skills\/chief-of-staff/);
});

test("installs a GitHub shorthand source with --agent as the profile selector", async () => {
  const gitEnv = await createFakeGitClone(fixture, "https://github.com/pablof7z/touch-grass.git");
  const result = runCli([
    "add",
    "pablof7z/touch-grass",
    "--agent",
    "ios-tester",
    "--global",
    "--home",
    home,
    "--json"
  ], gitEnv);
  assert.equal(result.status, 0, result.stderr);

  const parsed = JSON.parse(result.stdout);
  assert.equal(parsed.operations[0].profile, "ios-tester");
  assert.equal(parsed.operations[0].harness, "codex");
  assert.equal(parsed.operations[0].source, "pablof7z/touch-grass");
  assert.equal(existsSync(path.join(home, ".codex", "ios-tester.config.toml")), true);
});

test("uses --harness to choose a target when --agent selects the profile", async () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "ios-tester",
    "--harness",
    "opencode",
    "--global",
    "--home",
    home,
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const parsed = JSON.parse(result.stdout);
  assert.equal(parsed.operations[0].profile, "ios-tester");
  assert.equal(parsed.operations[0].harness, "opencode");
  assert.equal(existsSync(path.join(home, ".config", "opencode", "agents", "ios-tester.md")), true);
});

test("installs Claude Code and OpenCode profile renderings", async () => {
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "claude-code",
    "opencode",
    "--profile",
    "ios-ux-ui-critic",
    "--global",
    "--home",
    home,
    "--json"
  ]);
  assert.equal(result.status, 0, result.stderr);

  const claudeTarget = path.join(home, ".claude", "agents", "ios-ux-ui-critic.md");
  const opencodeTarget = path.join(home, ".config", "opencode", "agents", "ios-ux-ui-critic.md");
  assert.equal(existsSync(claudeTarget), true);
  assert.equal(existsSync(opencodeTarget), true);

  const claude = await fs.readFile(claudeTarget, "utf8");
  const opencode = await fs.readFile(opencodeTarget, "utf8");
  assert.match(claude, /name: ios-ux-ui-critic/);
  assert.match(claude, /model: opus/);
  assert.match(claude, /Installed identity: `ios-ux-ui-critic`/);
  assert.match(opencode, /mode: subagent/);
  assert.match(opencode, /edit: deny/);
  assert.match(opencode, /Installed identity: `ios-ux-ui-critic`/);
});

test("use renders a single profile without installing", () => {
  const result = runCli(["use", `${fixture}@ios-tester`, "--agent", "codex", "--home", home]);
  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /name = "ios-tester"/);
  assert.equal(existsSync(path.join(home, ".codex", "ios-tester.config.toml")), false);
});

test("prints detected harness run instructions after install", async () => {
  const fakeBin = await createFakeCommand("codex");
  const result = runCli([
    "add",
    fixture,
    "--agent",
    "chief-of-staff",
    "--home",
    home
  ], { PATH: fakeBin });

  assert.equal(result.status, 0, result.stderr);
  assert.match(result.stdout, /Run installed profiles:/);
  assert.match(result.stdout, /chief-of-staff via codex: codex --profile chief-of-staff/);
});

test("remove deletes only generated installs", async () => {
  const install = runCli([
    "add",
    fixture,
    "--agent",
    "codex",
    "--profile",
    "ios-tester",
    "--global",
    "--home",
    home
  ]);
  assert.equal(install.status, 0, install.stderr);

  const target = path.join(home, ".codex", "ios-tester.config.toml");
  assert.equal(existsSync(target), true);

  const remove = runCli(["remove", "ios-tester", "--agent", "codex", "--global", "--home", home, "--json"]);
  assert.equal(remove.status, 0, remove.stderr);
  assert.equal(existsSync(target), false);

  const registry = JSON.parse(await fs.readFile(path.join(home, ".awesome-agents", "installed.json"), "utf8"));
  assert.deepEqual(registry.installs, []);
});

async function createFakeCommand(command) {
  const fakeBin = path.join(tempRoot, `fake-${command}-bin`);
  const fakeCommand = path.join(fakeBin, command);
  await fs.mkdir(fakeBin, { recursive: true });
  await fs.writeFile(fakeCommand, "#!/bin/sh\nexit 0\n");
  await fs.chmod(fakeCommand, 0o755);
  return fakeBin;
}

async function createFakeGitClone(source, expectedUrl) {
  const fakeBin = path.join(tempRoot, "fake-bin");
  const fakeGit = path.join(fakeBin, "git");
  await fs.mkdir(fakeBin, { recursive: true });
  await fs.writeFile(fakeGit, `#!/usr/bin/env node
const fs = require("node:fs");
const path = require("node:path");

const [command, depthFlag, url, dest] = process.argv.slice(2);
if (command !== "clone" || depthFlag !== "--depth=1") {
  console.error(\`unexpected git args: \${process.argv.slice(2).join(" ")}\`);
  process.exit(2);
}
if (url !== process.env.AWESOME_AGENTS_EXPECTED_URL) {
  console.error(\`unexpected git url: \${url}\`);
  process.exit(2);
}

for (const entry of fs.readdirSync(process.env.AWESOME_AGENTS_FAKE_SOURCE)) {
  fs.cpSync(
    path.join(process.env.AWESOME_AGENTS_FAKE_SOURCE, entry),
    path.join(dest, entry),
    { recursive: true, force: true }
  );
}
`);
  await fs.chmod(fakeGit, 0o755);

  return {
    AWESOME_AGENTS_EXPECTED_URL: expectedUrl,
    AWESOME_AGENTS_FAKE_SOURCE: source,
    PATH: `${fakeBin}${path.delimiter}${process.env.PATH ?? ""}`
  };
}

function runCli(args, envOverrides = {}, options = {}) {
  return spawnSync(process.execPath, [bin, ...args], {
    cwd: options.cwd ?? repoRoot,
    encoding: "utf8",
    env: {
      ...process.env,
      HOME: home,
      CODEX_HOME: "",
      CLAUDE_HOME: "",
      OPENCODE_CONFIG_DIR: "",
      XDG_CONFIG_HOME: "",
      ...envOverrides
    }
  });
}
