export const PACKAGE_NAME = "awesome-agents";
export const PACKAGE_VERSION = "0.1.3";
export const DEFAULT_AGENT = "codex";
export const SUPPORTED_AGENTS = ["codex", "claude-code", "opencode"];
export const REGISTRY_DIRNAME = ".awesome-agents";
export const REGISTRY_FILENAME = "installed.json";
export const GENERATED_MARKER = "Generated by awesome-agents";

export const AGENT_ALIASES = new Map([
  ["codex", "codex"],
  ["openai", "codex"],
  ["openai-codex", "codex"],
  ["claude", "claude-code"],
  ["claude-code", "claude-code"],
  ["claudecode", "claude-code"],
  ["opencode", "opencode"],
  ["open-code", "opencode"]
]);
